<a href="https://colab.research.google.com/github/jon890613/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
#建立陣列 
ar2=np.array([[1,3,5],[2,8,7]]) # 2 * 3 的陣列

In [ ]:
#陣列的shape(形狀) and dimension(維度)
print("ar2.ndim ->",ar2.ndim)  #維度
print("ar2.shap ->e",ar2.shape) #形狀(tuple的資料形式)
print("ar2.shape[0] ->",ar2.shape[0])
print("ar2.shape[1] ->",ar2.shape[1])

ar2.ndim -> 2
ar2.shap ->e (2, 3)
ar2.shape[0] -> 2
ar2.shape[1] -> 3


In [ ]:
#陣列的資料型態(dtype)與型態轉換(astype)
ar= np.array([2,4,6,8])
print("ar.dtype ->",ar.dtype) #資料型態(dtype)


ar= np.array([2,4,6,8], dtype = float); 
print("ar.dtype ->",ar.dtype)


ar = np.array([2.,4,5,8]) # 2.判定為float
print("ar.dtype ->",ar.dtype)


f_ar = np.array([13,-3,8.88])
print("f_ar ->",f_ar)
print("f_ar.dtype ->",f_ar.dtype)


intf_ar=f_ar.astype(int)  #型態轉換(astype)
print("intf_ar ->",intf_ar)
print("intf_ar.dtype ->",intf_ar.dtype)

ar.dtype -> int64
ar.dtype -> float64
ar.dtype -> float64
f_ar -> [13.   -3.    8.88]
f_ar.dtype -> float64
intf_ar -> [13 -3  8]
intf_ar.dtype -> int64


In [ ]:
#建立array的方法

print("np.zeros((2,3)) ->\n",np.zeros((2,3))) #建立2*3都為0的陣列

print("np.arange(2,3,0.1) ->",np.arange(2,3,0.1)) #star,end,step

print("np.linspace(1,4,6) ->",np.linspace(1,4,6)) #star,end,num 切成num等分

print("np.indices((3,3)) ->\n",np.indices((3,3))) #產生 3 3 的索引陣列

print("np.linspace(2,3,5,endpoint=False) ->",np.linspace(2,3,5,endpoint=False))

print("np.linspace(2,3,5,retstep=True) ->",np.linspace(2,3,5,retstep=True))

print("np.eye(3) ->\n",np.eye(3)) #生成對角矩陣(值為1)
print("np.diag((2,4,6,8))->\n",np.diag((2,4,6,8)))  #生成對角線矩陣


np.zeros((2,3)) ->
 [[0. 0. 0.]
 [0. 0. 0.]]
np.arange(2,3,0.1) -> [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
np.linspace(1,4,6) -> [1.  1.6 2.2 2.8 3.4 4. ]
np.indices((3,3)) ->
 [[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]
np.linspace(2,3,5,endpoint=False) -> [2.  2.2 2.4 2.6 2.8]
np.linspace(2,3,5,retstep=True) -> (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)
np.eye(3) ->
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
np.diag((2,4,6,8))->
 [[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]
[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [ ]:
print(np.array([range(i,i+3)for i in [2,4,6]]))

[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [ ]:
a = np.array([0,1,2])
print(a)

[0 1 2]


In [ ]:
data = np.random.randn(2,3)
print(data)

[[-0.76505306 -0.43454336  0.14432207]
 [ 0.45647399  0.1271756  -0.54305463]]


In [ ]:
data = np.random.uniform(1,5,5)
print(data)

[4.90609656 3.58347658 1.37179701 3.87114029 1.34274464]


In [ ]:
sum(data)

15.075255069891961

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(10) * 10 

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [ ]:
np.arange(10) #產生出陣列

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1=np.ones((2,2))
arr2=np.array(arr1)
arr3=np.asarray(arr1)
arr1[0]=2
print("arr1=\n",arr1)
print("arr2=\n",arr2)
print("arr3=\n",arr3)

arr1=
 [[2. 2.]
 [1. 1.]]
arr2=
 [[1. 1.]
 [1. 1.]]
arr3=
 [[2. 2.]
 [1. 1.]]


In [ ]:
a = np.empty([2,2],int)
print(a)

[[4611686018427387904 4611686018427387904]
 [4607182418800017408 4607182418800017408]]
